name: Packer CI Pipeline

on:
    pull_request:
        branches:
            - main

jobs:
    packer:
        runs-on: ubuntu-latest
        steps:
            - name: Check out repository code
              uses: actions/checkout@v4

            - name: Setup `packer`
              uses: hashicorp/setup-packer@main
              id: setup
              with:
                  version: "latest"

            - name: Run packer `init`
              id: init
              run: "packer init ."
              working-directory: ./packer

            - name: Run packer `fmt`
              id: fmt
              run: "packer fmt ."
              working-directory: ./packer

            - name: Run packer `validate`
              id: validate
              run: |
                  zip -r webapp.zip .
                  packer validate .
              working-directory: ./packer
